### ISSUE TITLE
XChaCha20 support

### ISSUE THREAD

**Issue by tuupola** [1ma/branca-erl#1]
It seems that it is possible to provide XChaCha20 support if the crypto library has ChaCha20 and HChaCha20. I think libsodium 1.0.11 has them both.

https://tools.ietf.org/html/draft-arciszewski-xchacha-00#section-2.3.1

```
xchacha20_encrypt(key, nonce, plaintext):
           subkey = hchacha20(key, nonce[0:15])
           return chacha20_encrypt(subkey, nonce[16:23], plaintext)
```

https://tools.ietf.org/html/draft-arciszewski-xchacha-00#section-2.3

```
XChaCha20 can be constructed from an existing ChaCha20 implementation
and HChaCha20.  All one needs to do is:

   1.  Pass the key and the first 16 bytes of the 24-byte nonce to
       HChaCha20 to obtain the subkey.

   2.  Use the subkey and remaining 8 byte nonce with ChaCha20 as normal
       (prefixed by 4 NUL bytes, since [RFC7539] specifies a 12-byte
       nonce).
```

I found this while reading through [Rust implementation](https://github.com/return/branca) source.

**Comment by 1ma** [comment]
Solved in 0.3.0 by switching to a more up-to-date libsodium binding that has the XChaCha20 variant.

Better late than never, I guess :)
